### ISSUE TITLE
How to run in no-GPU system?

### ISSUE THREAD

**Issue by hemangjoshi37a** [salesforce/CodeGen#8]
How to run in no-GPU system?

It gives me error No CUDA GPUs are available because I dont have any NVIDIA graphics card.

**Comment by rooa** [comment]
Hi Hemang, the default device in the script is the first GPU in your machine. You would have to specify the device: `--device cpu` when sampling.

Related to this, I added a commit to turn off half precision when using CPU (ffd5a9b38bc35ba5cd5d977b9dac8e0ef629725b) so that it doesn't encounter a RuntimeError. Please pull latest code before trying again.
